### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by sayan1999** [GavinPHR/Multi-Agent-Path-Finding#1]
I was trying with my own configuration but it gives this error for my scenario:

```
---
GOAL:
- !!python/tuple [9, 5]
- !!python/tuple [2, 2]
- !!python/tuple [6, 5]
- !!python/tuple [4, 10]
GRID_SIZE: 12
RECT_OBSTACLES:
  0:
  - [1, 7]
  - [3, 9]
  1:
  - [8, 3]
  - [9, 4]
  2:
  - [3, 1]
  - [4, 3]
  3:
  - [8, 9]
  - [9, 10]
ROBOT_RADIUS: 2
START:
- !!python/tuple [0, 0]
- !!python/tuple [0, 11]
- !!python/tuple [2, 11]
- !!python/tuple [2, 0]
```

Error:
```
Traceback (most recent call last):
  File "visualizer.py", line 146, in <module>
    r = Simulator()
  File "visualizer.py", line 28, in __init__
    self.planner = Planner(GRID_SIZE, ROBOT_RADIUS, static_obstacles)
  File "/home/sayan/anaconda3/lib/python3.8/site-packages/cbs_mapf/planner.py", line 31, in __init__
    self.st_planner = STPlanner(grid_size, robot_radius, static_obstacles)
  File "/home/sayan/anaconda3/lib/python3.8/site-packages/stastar/planner.py", line 30, in __init__
    self.neighbour_table = NeighbourTable(self.grid.grid)
  File "/home/sayan/anaconda3/lib/python3.8/site-packages/stastar/neighbour_table.py", line 15, in __init__
    dimy, dimx = len(grid), len(grid[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

```

Seems like my yaml file is wrong. Could you help me figure that out.

**Comment by itaihay** [comment]
Having the same issue. From what I saw in the example YAML I think we have the wrong idea of how the grid is constructed. It uses a grid=30. I assumed that it meant that the grid is 30x30, but the obstacles have far greater coordinates. 

Here's my YAML:
```
---
GOAL:
- !!python/tuple [39, 39]
- !!python/tuple [49, 49]

GRID_SIZE: 50
RECT_OBSTACLES:
  0:
  - [0, 2]
  - [11, 15]
  1:
  - [20, 8]
  - [40, 10]
  2:
  - [15, 16]
  - [41, 24]
  3:
  - [45, 16]
  - [50, 25]

ROBOT_RADIUS: 1
START:
- !!python/tuple [0, 0]
- !!python/tuple [49, 0]
```

**Comment by sayan1999** [comment]
Is this YAML of yours working?

**Comment by sayan1999** [comment]
Then what does grid=30 mean?

**Comment by gitLouis** [comment]
to my understanding grid_size is defining the size of each "square" in the grid (aka edge-length). For instance,
 grid_size = 1 means that the state space is [[0,0],[0,1],[1,0],[1,1], ...]
 grid_size = 2 means that the state space is [[0,0],[0,2],[2,0],[2,2], ...].
 grid_size =30 means that the state space is [[0,0],[0,30],[30,0],[30,30], ...].


Then if you put static_obstacle or location off this grid it is rounded to the grid. e.g. if grid_size = 30 and obstacle is on (5,5) then it might be removed or rounded to (0,0). I didn't check the exact rounding procedure and behavior here.

The state-space boundaries are then defined by the minimal and maximal obstacles. see for instance in `calculate_boundaries` where `min_ = np.min(static_obstacles, axis=0)`

In @sayan1999's code all the values are smaller than grid-size, hence the weird behavior (maybe all the obstacles and the locations are rounded down to (0,0)). probably you are getting zero-dimension grid.

on the other hand, in @itaihay's example, you already have at least 2 actual points. grid_size=50 and you have obstacles in (0,0) but also (50, 25 ) is rounded to grid point (50,0) and therefore you have a proper grid.

**Comment by GavinPHR** [comment]
Sorry for the late reply, but @gitLouis is correct on this issue. 
In my original use case, I had a 1080p raw grid (from a camera feed) and did not require such a high resolution (plus it's very slow to plan on such a big grid).
`grid_size` effectively splits your raw grid into patches, set it to 1 otherwise.
